version: "2.1"
services:
  app:
    # replace imageName with your image name (block in your case)
    image: prova-java
    ports:
      - 8092:8080 # Replace the port of your application here if used
    depends_on:
      - postgres
    networks:
      - provaJava

