create table customer (id int8 generated by default as identity, company varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), primary key (id))

create table permissao (id int8 generated by default as identity, nome varchar(255), user_id int8, primary key (id))

create table usuario (id int8 generated by default as identity, email varchar(255) not null, senha varchar(255) not null, primary key (id))

alter table if exists customer add constraint UK_dwk6cx0afu8bs9o4t536v1j5v unique (email)

alter table if exists usuario add constraint UK_5171l57faosmj8myawaucatdw unique (email)

alter table if exists permissao add constraint FKkj3nnfwlk5d3dn0ir0cfijlg3 foreign key (user_id) references usuario
